config/routes.rb
Konacha::Engine.routes.draw do
  get '/iframe/*name' => 'specs#iframe', :format => false, :as => :iframe
  root :to    => 'specs#parent'
  get '*path' => 'specs#parent', :format => false
end

app/models/konacha/spec.rb
module Konacha
  class Spec
    class NotFound < StandardError
    end

    def self.all(path = nil)
      paths = Konacha.config.spec ? Konacha.config.spec : Konacha.spec_paths
      paths = paths.map { |p| new(p) }
      if path.present?
        paths = paths.select { |s| s.path.starts_with?(path) }.presence or raise NotFound
      end
      paths
    end

    def self.find_by_name(name)
      all.find { |s| s.asset_name == name } or raise NotFound
    end

    attr_accessor :path

    def initialize(path)
      @path = path
    end

    def asset_name
      path.sub(/(\.js|\.coffee).*/, '')
    end
  end
end

app/models/matcha/spec.rb
module Matcha
  class Spec
    def self.all
      Matcha.spec_paths.map { |path| new(path) }
    end

    def self.find(basename)
      all.find { |spec| spec.basename == basename }
    end

    attr_accessor :path

    def initialize(path)
      @path = path
    end

    def url
      "/#{basename}"
    end

    def basename
      path[/.*(?=\.js.*$)/]
    end
  end
end

app/controllers/konacha/fixtures_controller.rb
module Konacha
  class FixturesController < ActionController::Base
    def fixtures
      render  :file => "#{Rails.root}#{request.env['REQUEST_PATH']}"
      rescue ActionView::MissingTemplate
        render :text => "Not found", :status => 404
    end
  end
end

app/controllers/konacha/specs_controller.rb
module Konacha
  class SpecsController < ActionController::Base
    rescue_from Konacha::Spec::NotFound do
      if Konacha.rails_5_x?
        render plain: "Not found", status: 404
      else
        render :text => "Not found", :status => 404
      end
    end

    def parent
      @run_mode = params.fetch(:mode, Konacha.mode).to_s.inquiry
      @specs = Konacha::Spec.all(params[:path])
    end

    def iframe
      @spec = Konacha::Spec.find_by_name(params[:name])
      @stylesheets = Konacha::Engine.config.konacha.stylesheets
      @javascripts = Konacha::Engine.config.konacha.javascripts
    end
  end
end

app/controllers/matcha/specs_controller.rb
module Matcha
  class SpecsController < ActionController::Base
    before_filter :set_interface, :set_mode

    def set_interface
      @interface = Matcha.interface
    end

    def set_mode
      @mode = Matcha.mode
    end

    def index
      @specs = Matcha::Spec.all
    end

    def show
      @spec = Matcha::Spec.find(params[:spec])
      @spec or render :text => "Not Found", :status => 404
    end
  end
end

app/views/konacha/specs/iframe.html.erb
<!doctype html>
<html data-path="<%= @spec.path %>">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Konacha Tests</title>

    <% @stylesheets.each do |file| %>
      <%# Use :debug => false for stylesheets to improve page load performance. %>
      <%= stylesheet_link_tag file, :debug => false %>
    <% end %>

    <%= javascript_include_tag *@javascripts, :debug => false %>
    <%= javascript_include_tag @spec.asset_name %>
  </head>
  <body>
  </body>
</html>

app/views/konacha/specs/parent.html.erb
<!doctype html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Konacha Tests</title>
    <%= stylesheet_link_tag "konacha", :debug => false %>
    <%= javascript_include_tag "mocha", "konacha/parent", :debug => false %>
    <%= javascript_include_tag("konacha/runner", :debug => false) if @run_mode.runner? %>
  </head>
  <body>
    <% @specs.each do |spec| %>
      <%= content_tag :iframe, "", :src => spec_path(spec), :class => "test-context", "data-path" => spec.path %>
    <% end %>
    <div id="mocha"></div>
  </body>
</html>

app/views/konacha/specs/reporter.html.erb
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Konacha Tests</title>
    <%= stylesheet_link_tag "konacha", :debug => false %>
  </head>
  <body>
    <%= content_tag :iframe, '', :src => @iframe_path, :id => 'test-context' %>
    <div id="mocha"></div>
  </body>
</html>

app/views/konacha/specs/runner.html.erb
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Konacha Tests</title>

    <% @stylesheets.each do |file| %>
      <%# Use :debug => false for stylesheets to improve page load performance. %>
      <%= stylesheet_link_tag file, :debug => false %>
    <% end %>

    <%= javascript_include_tag "mocha", "chai", "konacha/#{Konacha.mode}", :debug => false %>

    <%= spec_include_tag *@specs %>
  </head>
  <body>
  </body>
</html>

app/views/konacha/specs/specs.html.erb
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Konacha Tests</title>

    <% @stylesheets.each do |file| %>
      <%# Use :debug => false for stylesheets to improve page load performance. %>
      <%= stylesheet_link_tag file, :debug => false %>
    <% end %>

    <%= javascript_include_tag "mocha", "chai", "konacha/#{Konacha.mode}", :debug => false %>

    <%= spec_include_tag *@specs %>
  </head>
  <body>
  </body>
</html>

app/views/layouts/konacha/specs.html.erb
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Mocha Tests</title>
    <%= stylesheet_link_tag "mocha" %>
    <%= stylesheet_link_tag "konacha" %>
    <%= javascript_include_tag "jquery", "mocha", "chai", "konacha/#{@mode}" %>
    <script>
      mocha.setup(<%= raw @interface.to_json %>);
      var expect = chai.expect,
          should = chai.should(),
          assert = chai.assert;

      window.onload = function () {
        mocha.run(Konacha.Reporter);
      };

      <% if @interface == :bdd %>
        beforeEach(function() {
          document.getElementById('test').innerHTML = "";
        });
      <% elsif @interface == :tdd %>
        setup(function() {
          document.getElementById('test').innerHTML = "";
        });
      <% end %>
    </script>
    <%= yield %>
  </head>
  <body>
    <div id="mocha"></div>
    <div id="test"></div>
  </body>
</html>

app/views/layouts/matcha/specs.html.erb
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <title>Mocha Tests</title>
    <%= stylesheet_link_tag "mocha" %>
    <%= javascript_include_tag "jquery", "mocha", "chai", "matcha/#{@mode}" %>
    <script>
      mocha.setup(<%= raw @interface.to_json %>);
      var expect = chai.expect,
          should = chai.should(),
          assert = chai.assert;
      window.onload = mocha.run;

      <% if @interface == :bdd %>
        beforeEach(function() {
          document.getElementById('test').innerHTML = "";
        });
      <% elsif @interface == :tdd %>
        setup(function() {
          document.getElementById('test').innerHTML = "";
        });
      <% end %>
    </script>
    <%= yield %>
  </head>
  <body>
    <div id="mocha"></div>
    <div id="test"></div>
  </body>
</html>